assembly.o: assembly.S
boot.o: boot.S multiboot.h x86_desc.h types.h page.h
page_assembly.o: page_assembly.S
x86_desc.o: x86_desc.S x86_desc.h types.h page.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c x86_desc.h types.h page.h lib.h i8259.h idt.h rtc.h \
  keyboard.h assembly.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h page.h lib.h i8259.h \
  debug.h tests.h rtc.h assembly.h keyboard.h
keyboard.o: keyboard.c x86_desc.h types.h page.h lib.h i8259.h keyboard.h
lib.o: lib.c lib.h types.h
page.o: page.c page_assembly.h x86_desc.h types.h page.h
rtc.o: rtc.c rtc.h lib.h types.h i8259.h
tests.o: tests.c tests.h x86_desc.h types.h page.h lib.h
